---
title: "TIP-RA Metaclustering for DISCOV-R"
author: "Virginia Muir, Kaitlin Flynn, Matt Dufort"
date: "2023-05-10"
output: html_document
---


```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Session options
options(stringsAsFactors = FALSE)
set.seed(12345)

library(knitr)
opts_chunk$set(echo = F, message = F, warning = F, cache = T)

# Set up the environment with required packages
if (!require(ComplexHeatmap)) BiocManager::install("ComplexHeatmap"); library(ComplexHeatmap)
if (!require(circlize)) install.packages("circlize"); library(circlize)
if (!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)
if (!require(magrittr)) install.packages("magrittr"); library(magrittr)
if (!require(reshape2)) install.packages("reshape2"); library(reshape2)
if (!require(ggthemes)) install.packages("ggthemes"); library(ggthemes)
if (!require(viridis)) install.packages("viridis"); library(viridis)
if (!require(RColorBrewer)) install.packages("RColorBrewer"); library(RColorBrewer)
if (!require(ggmosaic)) install.packages("ggmosaic"); library(ggmosaic)
if (!require(grid)) install.packages("grid"); library(grid)
if (!require(gridExtra)) install.packages("gridExtra"); library(gridExtra)
if (!require(hypergate)) install.packages("hypergate"); library(hypergate)
```

```{r set_working_directory, cache=FALSE}
# Set working directory 
## (This isn't strictly required, since Rmarkdown will use whatever folder this script is stored in as the working directory, but I find it useful for troubleshooting in the console.)
## A windows version would look like:
## setwd("~\Grandparent folder\Parent folder\Folder where this script and your data folders are")
dir_root <-
  file.path("~", "Library", "CloudStorage", "Box-Box", "Projects",
            "TIP_RA_cross_sectional_simplified")
setwd(dir_root)
opts_knit$set(root.dir = dir_root)
```

```{r set_directories_and_global_variables}
# Set up the ggplot default params
theme_set(
  theme_bw(12) + 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          plot.title = element_text(size=15, face="bold", margin = margin(10,0,10,0)),
          axis.text.x = element_text(angle=45, hjust = 1)))

# Heatmap-relevant options
linkage = "ward.D2" # complete = Mario's choice; average = pvclust default; ward.D2 = sigclust2 default
distance = "euclidean" # manhattan = Mario's choice; cor = pvclust default; euclidean = sigclust2 default
export_width = 600
export_height = 600
title_font_gp = gpar(fontface = "bold", fontsize = 15)
marker_label_gp = gpar(fontsize = 13)
legend_params = list()
tmrs <- c("agg", "cilp", "eno", "vf", "flu", "none")
markers = c("CD45RA", "CD38", "CCR4", "CCR6", "CCR7", "CXCR3")

# Set up filename prefixes and output folders with the data
dir_data <- file.path(dir_root, "data")

path_stem <- file.path(dir_root, "output")
dir.create(path_stem)
dir_heatmaps <- file.path(path_stem, "heatmaps"); dir.create(dir_heatmaps)
dir_mosaic_plots <- file.path(path_stem, "mosaic_plots"); dir.create(dir_mosaic_plots)
dir_dotplots <- file.path(path_stem, "dotplots"); dir.create(dir_dotplots)
dir_data_output <- file.path(path_stem, "data_output"); dir.create(dir_data_output)
```


```{r get_shared_data}
# Designate which data you'd like to load (generated by TIP_RA_clustering_simplified.Rmd)
data_path =
  file.path("output", "R_objects", "all_phenograph_data.RData")

# Load data frame from initial clustering using RPhenograph
load(data_path)

# ID any samples that may have too few events.
event_check = as.data.frame(table(mergedExpr$sample))
# event_check %>% dplyr::filter(Freq < 10000) %>% select(Var1) 

# This can be used to drop a subset of the samples from your analysis. 
drop_samples <- event_check$Var1[event_check$Freq < 10000] %>%
  as.character()
# 11 samples identified to drop

# MD added this ungrouping step for compatibility with new R package versions
RPtmr_counting <- ungroup(RPtmr_counting)
RP_mean <- ungroup(RP_mean)

RPtmr_counting$RPclust <- as.character(RPtmr_counting$RPclust)
RPtmr_counting = RPtmr_counting %>%
  left_join(RP_mean, by = c("sample", "RPclust")) %>%
  subset(!(sample %in% drop_samples))
# dropping 11 samples cuts from 1478 rows to 1339 rows

RP_mean = RP_mean %>% subset(!(sample %in% drop_samples)) # from 1563 to 1413 rows
mergedExpr = mergedExpr %>% 
  subset(!(sample %in% drop_samples)) %>%
  mutate(RPclust = as.character(RPclust))
# from 2842350 rows to 2790282 rows
 
# Identify low abundance clusters (containing <1% of events per subject) 
RPtmr_counting = RPtmr_counting %>% 
  ungroup() %>% 
  mutate(pct_cells_in_clust = clust_size/clust_size_tot*100, 
         keep = pct_cells_in_clust >= 1)
 
# Filter out low abundance clusters (do this after calculating z-scores??)
drop_clusters = dplyr::filter(RPtmr_counting, keep == F) %>%
  dplyr::select(sample, RPclust)
# 34 sample/cluster combinations to drop

RPtmr_counting = RPtmr_counting %>% anti_join(drop_clusters) # from 1339 rows to 1305 rows
mergedExpr = mergedExpr %>% anti_join(drop_clusters) # from 2790282 rows to 2781208 rows
RP_mean = RP_mean %>% anti_join(drop_clusters) # from 1413 rows to 1379 rows

## Prep to calculate z-scores
# Compute the per-subject/per-cluster standard deviation so that I can later compute z-score
RP_sd <- mergedExpr %>%
  dplyr::select(-tmr_pos, -contains("tsne"), -contains("umap")) %>%
  group_by(sample, RPclust) %>%
  summarise_all(sd)

# Calculate CD4 standard deviations for each sample
CD4_sd <- mergedExpr %>%
  dplyr::select(-tmr_pos, -RPclust, -contains("tsne"), -contains("umap")) %>%
  group_by(sample) %>%
  summarise_all(sd) %>%
  mutate(RPclust = "Total_CD4")

# Merge per-cluster and total CD4 standard deviations
RP_sd = bind_rows(RP_sd, CD4_sd)

# format mean/var data for ease of use
sample_means = RP_mean %>%
  dplyr::filter(RPclust == "Total_CD4") %>%
  dplyr::select(-RPclust) %>%
  gather("marker", "subject_mean", -sample) %>%
  dplyr::rename(subject = sample)

sample_sds = RP_sd %>%
  dplyr::filter(RPclust == "Total_CD4") %>%
  dplyr::select(-RPclust) %>%
  gather("marker", "subject_sd", -sample) %>%
  dplyr::rename(subject = sample)

df_mean_var <-
  left_join(sample_means, sample_sds, by = c("subject", "marker")) %>%
  mutate(subject_var = subject_sd **2)
```

```{r set_colors, echo=FALSE, message=FALSE, warning=FALSE}
# Set up a palette for the heatmap
my_zscore_pal <- colorRamp2(c(-2,0,2), c("#00ffffFF", "#000000FF", "#FDE725FF"))
# my_zscore_pal <- colorRamp2(c(-3,0,3), c("#00ffffFF", "#000000FF", "#FDE725FF"))

# get subject ids, assign colors to them
subject_ids <- sort(unique(mergedExpr$sample))
subject_id_colors <- 
  data.frame(subject = subject_ids,
             #color = rainbow(length(subject_ids)))
             color = c("#000000FF",
                       plasma(length(subject_ids)+2)[4:(length(subject_ids)+2)]))

pass_threshold_colors <- data.frame(pass = c(T,F), color = c("#FF0000", "#888888"))

# Use Hannah/Virginia's color palette for matching to cluster colors
cb_pal <- colorblind_pal()(8)[-1]
tol_cb_pal <-
  setNames(c("#332288", "#117733", "#44AA99", "#88CCEE", 
             "#DDCC77", "#CC6677", "#AA4499", "#882255"),
           as.character(1:8))
tableau_10 <- ggthemes::tableau_color_pal(palette = "Tableau 10", direction = 1)(10)
```

## ==================================================================
## Gather Clusters from Subjects (both containing and excluding Tmrs)
## ==================================================================

```{r get_all_cluster_data}
# prepare data for each tmr
df_sig_list <- list()
hmap_df_list <- list()
persub_zscore_list <- list()
persub_arcsinh_list <- list()

for (t in tmrs){
  # filter out clusters with no Tmr+ cells
  df_sig_list[[t]] <-
    RPtmr_counting %>%
    dplyr::rename(subject = sample) %>%
    dplyr::filter(!!rlang::sym(t) > 0) # tweaked 2022-02-14 to use filter() because filter_() was deprecated

  # set up data frames for plotting
  hmap_df_list[[t]] <-
    df_sig_list[[t]] %>%
    dplyr::select(subject, RPclust, one_of(markers)) %>%
    melt(id.vars = c("subject", "RPclust")) %>% 
    dplyr::rename(marker = variable, mean = value) %>%
    merge(df_mean_var, by=c("subject", "marker")) %>%
    mutate(zscore_persub = (mean - subject_mean)/subject_sd,
           arcsinh_persub = mean,
           sample = paste0(.$subject, "_", .$RPclust)) %>%
    dplyr::select(marker, zscore_persub, arcsinh_persub, sample)
  
  # Extract the z-scores
  persub_zscore_list[[t]] <-
    hmap_df_list[[t]] %>%
    dcast(marker ~ sample, value.var = "zscore_persub") %>%
    set_rownames(.$marker) %>%
    dplyr::select(-marker)
  
  # Extract the arcsinh transformed fluorescence values
  persub_arcsinh_list[[t]] <- 
    hmap_df_list[[t]] %>%
    dcast(marker ~ sample, value.var = "arcsinh_persub") %>%
    set_rownames(.$marker) %>%
    dplyr::select(-marker)
}

rm(t)
```

##====================================
## Combine all Subjects all Clusters
##====================================

```{r get_all_tmr_clusters_data}
# load expression data, select all unique clusters 
df_all_tmr <- NULL
for (t in tmrs){
  df_all_tmr <- rbind(df_all_tmr, df_sig_list[[t]]) %>% unique
}

## Include regardless of colorbar visualization
clust_sig_pass <-
  df_all_tmr %>%
  select(subject, RPclust, all_of(tmrs)) %>%
  mutate(sample = paste0(.$subject, "_", .$RPclust))

tmr_counting <- clust_sig_pass %>% select(sample, all_of(tmrs))

## Include to show % of Tmrs/Specificity present in a cluster for each individual 
clust_sig_pass %<>% group_by(subject) %>%
  mutate(tot_agg = sum(agg), 
         tot_cilp = sum(cilp),
         tot_eno = sum(eno), 
         tot_vf = sum(vf), 
         tot_flu = sum(flu), 
         tot_none = sum(none)) %>%
  ungroup() %>%
  mutate(agg = agg/tot_agg, 
         cilp = cilp/tot_cilp,
         eno = eno/tot_eno, 
         vf = vf/tot_vf, 
         flu = flu/tot_flu, 
         none = none/tot_none)

clust_sig_pass = clust_sig_pass %>%
  mutate_at(vars(tmrs), round, digits = 2) %>%
  dplyr::select(sample, tmrs)

clust_sig_pass <- replace(clust_sig_pass, is.na(clust_sig_pass), 0)

## Create data object
hmap_df_all_tmr <- 
  df_all_tmr %>%
  select(subject, RPclust, one_of(markers)) %>% 
  melt(id.vars = c("subject", "RPclust")) %>% 
  dplyr::rename(marker = variable, mean = value) %>%
  merge(df_mean_var, by=c("subject", "marker")) %>%
  ## Apply z-score here!
  mutate(zscore_persub = (mean - subject_mean)/subject_sd,
         arcsinh_persub = mean,
         sample = paste0(.$subject, "_", .$RPclust)) %>%
  select(sample, subject, marker, zscore_persub, arcsinh_persub) %>%
  merge(clust_sig_pass, by="sample")
 

# Extract the z-scores for all subjects
all_tmr_all_sub_persub_zscores <-
  hmap_df_all_tmr %>%
  dcast(marker ~ sample, value.var = "zscore_persub") %>%
  set_rownames(.$marker) %>%
  select(-marker)

# extract the z-scores for each subject, and mark which clusters pass the threshold
all_tmr_persub_zscores <- list()
for (s in unique(hmap_df_all_tmr$subject)){
  all_tmr_persub_zscores[[s]] <- 
    hmap_df_all_tmr %>%
    dplyr::filter(subject == s) %>%
    dcast(marker ~ sample, value.var = "zscore_persub") %>%
    set_rownames(.$marker) %>%
    select(-marker)
}

# Extract the arcsinh fluorescence values for all subjects
all_tmr_all_sub_persub_arcsinh <-
  hmap_df_all_tmr %>%
  dcast(marker ~ sample, value.var = "arcsinh_persub") %>%
  set_rownames(.$marker) %>%
  select(-marker)

# extract the arcsinh fluorescence values for each subject, and mark which clusters pass the threshold
all_tmr_persub_arcsinh <- list()
for (s in unique(hmap_df_all_tmr$subject)){
  all_tmr_persub_arcsinh[[s]] <- 
    hmap_df_all_tmr %>%
    dplyr::filter(subject == s) %>%
    dcast(marker ~ sample, value.var = "arcsinh_persub") %>%
    set_rownames(.$marker) %>%
    select(-marker)
}

rm(s, t)
```

##====================================
## Create metacluster & summary heatmaps
##====================================

```{r enriched_cluster_zscore_hmap_by_tmr_mario}
all_tmr_zscore_anno_df <- 
  hmap_df_all_tmr %>% 
  ungroup() %>%
  dplyr::select(sample, tmrs) %>%
  unique() %>%
  slice(match(colnames(all_tmr_all_sub_persub_zscores), .$sample)) %>% 
  mutate(sample = str_replace(.$sample, "_[0-9]+$", "")) %>%
  dplyr::rename(subject = sample) # %>%
  # left_join(select(clinical_vars, ID, progression = `Progression rate`, duration = Duration), by = c("subject" = "ID"))

my_hm <- Heatmap(all_tmr_all_sub_persub_zscores,
          clustering_method_columns = linkage,
          clustering_method_rows = linkage)

# cut the dendrogram to get phenotypic metaclusters
n_metaclusters = 10
col_clust <- as.hclust(column_dend(my_hm))
col_indices <- cutree(col_clust, k = n_metaclusters)
# ordered_indices <- col_indices[column_order(my_hm)]

mc1_clusts = names(which(col_indices == 1))
mc2_clusts = names(which(col_indices == 2))
mc3_clusts = names(which(col_indices == 3))
mc4_clusts = names(which(col_indices == 4))
mc5_clusts = names(which(col_indices == 5))
mc6_clusts = names(which(col_indices == 6))
mc7_clusts = names(which(col_indices == 7))
mc8_clusts = names(which(col_indices == 8))
mc9_clusts = names(which(col_indices == 9))
mc10_clusts = names(which(col_indices == 10))

# pull up unique(ordered_indices).  fill in the left side mc ids in order of the resulting vector.
##e.g. 4  7 10  1  3  9  8  5  6  2
col_indices[mc4_clusts] = 1
col_indices[mc7_clusts] = 2
col_indices[mc10_clusts] = 3
col_indices[mc1_clusts] = 4
col_indices[mc3_clusts] = 5
col_indices[mc9_clusts] = 6
col_indices[mc8_clusts] = 7
col_indices[mc5_clusts] = 8
col_indices[mc6_clusts] = 9
col_indices[mc2_clusts] = 10
  
plot_tmrs = c("agg", "cilp", "eno", "vf") # , "Insulin", "Virus"

# set up colors as a named list
all_tmr_zscore_anno_colors <-
  list(
    subject =
      setNames(subject_id_colors$color,
               as.character(subject_id_colors$subject)),
    group = setNames(tableau_10,
                     as.character(1:n_metaclusters))) #,
# group = setNames(viridis(k_groups),
#          as.character(unique(col_indices)))) # original viridis scheme

# add metacluster information to tmr counting information
tmr_counting = tmr_counting %>%
  left_join(data.frame(sample = colnames(all_tmr_all_sub_persub_zscores), group = col_indices))


## Use for pct tmrs color scheme
for (t in plot_tmrs){
  tmr_vect = all_tmr_zscore_anno_df %>% dplyr::select(all_of(t)) %>% unlist(use.names = FALSE)
  all_tmr_zscore_anno_colors[[t]] =
    c(setNames("white", 0), 
      setNames(colorRampPalette(c("grey95", "grey0"))(100), 
               seq(0.01, 1.00, 0.01)))
}

all_tmr_zscore_anno_df %<>% mutate(group = col_indices) %>%
  select(subject, group, all_of(plot_tmrs))

all_tmr_zscore_anno <-
  HeatmapAnnotation(
    df = data.frame(all_tmr_zscore_anno_df),
    col = all_tmr_zscore_anno_colors,
    show_annotation_name = T,
    show_legend = F)

zscore_hmap <- 
  Heatmap(all_tmr_all_sub_persub_zscores,
          col = my_zscore_pal,
          name = "z-score",
          column_title = paste0("Cluster Phenotypes from All Subjects"),
          column_title_gp = title_font_gp,
          clustering_method_columns = linkage,
          cluster_rows = F,
          row_order = c("CD45RA", "CD38", "CCR7", "CXCR3", "CCR4", "CCR6"),
          clustering_method_rows = linkage,
          show_column_names = F,
          row_names_gp = marker_label_gp,
          top_annotation = all_tmr_zscore_anno,
          heatmap_legend_param = legend_params)

png(file = 
      file.path(
        dir_heatmaps,
        paste0("Zscores-perSubj-YellowCyan_", linkage, "_", distance, "_", 
               "_AllClusters_cutree", n_metaclusters, "_pct_Tmr.png")),
    width = export_width,
    height = export_height)
print(zscore_hmap)
invisible(dev.off())
``` 

##====================================
## Data export
##====================================

```{r wrangle_and_export_data}
tmr_counting = tmr_counting %>%
  # extract everything after the last underscore
  mutate(RPclust = sapply(strsplit(tmr_counting$sample, "_"), tail, 1L), 
         subject = str_remove(tmr_counting$sample, "_[0-9]+$")) 

phenos =
  readxl::read_xlsx(
    file.path(dir_data, "TIPRA_CoreBaselineCohortAcceleratedAnalysis 26-Mar-2019.xlsx"), 
    na = c("NA", "Not tested", "999", "Missing"))

updated_converter_list =
  readxl::read_xlsx(
    file.path(dir_data, "TIP-RA Converters Summary 09-04-19 BRI.xlsx"),
    sheet = "Converters All Visits")

group_info_orig =
  phenos %>% 
  left_join(updated_converter_list %>%
              mutate(Labid = as.character(Labid)) %>%
              dplyr::select(ID, LABID = Labid, Analyze, RAConverter, DaysFromRADX),
            by = c("ID", "LABID")) %>%
  mutate(
    sample = paste0("lab", LABID),
    Analyze = 
      case_when(!is.na(Analyze.y) ~ Analyze.y, 
                TRUE ~ Analyze.x) %>%
      factor(
        levels =
          c("CCP_Neg_Baseline", "CCP_Pos_Baseline", "RA-Conv", "2ndYrRAConv", "RA_Baseline")),
    ccp_group = ifelse(Analyze == "CCP_Neg_Baseline", "Neg", "Pos") %>% 
      factor(levels = c("Neg", "Pos")),
    RA_group = ifelse(Analyze %in% c("RA_Baseline", "RA-Conv"), "RA", "No") %>%
      factor(levels = c("No", "RA")),
    RAConverter =
      case_when(!is.na(RAConverter.y) ~ RAConverter.y, 
                TRUE ~ RAConverter.x) %>%
      factor(levels = c("No", "Yes")),
    DaysFromRADX = 
      case_when(!is.na(DaysFromRADX.y) ~ DaysFromRADX.y, 
                TRUE ~ as.numeric(DaysFromRADX.x)),
    das28_cat = 
      case_when(DaS28CRP < 2.6 ~ "Near remission",
                DaS28CRP < 3.2 ~ "Low",
                DaS28CRP <= 5.1 ~ "Moderate",
                DaS28CRP > 5.1 ~ "High") %>%
      factor(levels = c("Near remission", "Low", "Moderate", "High"))) %>% 
  dplyr::select(
    donor_id = ID, sample, group = Analyze, ccp_group, RA_group,
    converter_group = RAConverter, age = Age, 
    sex = Gender, smoke = `Smoke Ever`, shared_epitope = `Shared Epitope (SE)`, 
    fdr_with_RA = FirstDegreeRelativeWithRA, bmi = BMI, ccp3_cont = CCP3Final, 
    ccp3_cat = CCP3Outcome, rf_IgA_cont = RFIgAFinal, rf_IgA_cat = RFIgAOutcome, 
    rf_IgM_cont = RFIgMFinal, rf_IgM_cat = RFIgMOutcome, crp_cont = CRPFinal, 
    crp_cat = CRPOutcome, das28_cont = DaS28CRP, das28_cat)

# remove RA converters from group_info
group_info =
  group_info_orig %>%
  dplyr::filter(
    group %in% c("CCP_Neg_Baseline", "CCP_Pos_Baseline", "RA_Baseline")
  ) %>%
  droplevels()

# combine info on cells and clusters with sample cluster/metacluster links
events_w_metaclust =
  mergedExpr %>% 
  left_join(tmr_counting %>% 
              dplyr::select(RPclust, sample = subject, metacluster = group)) 

# Quick look to see which clusters might be interesting
# this uses a hypergeometric distribution to test whether there are more RA tetramer-positive cells than expected in each metacluster (expect 18.8 per 100k events)
# events_w_metaclust %>% 
#   group_by(metacluster) %>% 
#   dplyr::summarise(tmrs = sum(tmr_pos %in% c("agg", "eno", "cilp", "vf")), total = n()) %>% 
#   mutate(
#     enr = phyper(tmrs-1, 
#                  sum(events_w_metaclust$tmr_pos %in% c("agg", "eno", "cilp", "vf")), 
#                  nrow(events_w_metaclust)-
#                    sum(events_w_metaclust$tmr_pos %in% c("agg", "eno", "cilp", "vf")), 
#                  total, lower.tail = F))
# metacluster 6 (strongly), metacluster 9 (pretty strong), metacluster 5 (pretty strong), metacluster 7 (weak)

tmr_distrib_for_export =
  tmr_counting %>%
  dplyr::select(
    subject, metacluster = group, RPclust, tmrs) %>%
  mutate(clust_size = none+agg+cilp+eno+vf+flu) %>%
  group_by(subject, metacluster) %>%
  dplyr::summarise(
    agg = sum(agg), cilp = sum(cilp), 
    eno = sum(eno), vf = sum(vf), ra = sum(agg, cilp, eno, vf),
    flu = sum(flu), total_events = sum(clust_size)) %>%
  ungroup() %>%
  tidyr::complete(
    subject, metacluster,
    fill = list(agg = 0, cilp = 0, eno = 0, vf = 0, ra = 0, flu = 0, total_events = 0))

fn = file.path(dir_data_output, "Metaclust_summary.csv")
write_csv(
  tmr_distrib_for_export %>%
    inner_join(group_info %>% dplyr::select(subject=sample, group) %>% unique()) %>%
    dplyr::select(subject, group, everything()), fn)

tmr_by_subj = tmr_counting %>%
  dplyr::select(subject, tmrs) %>%
  mutate(total = agg + cilp + eno + vf + flu + none,
         ra = agg + cilp + eno + vf) %>%
  group_by(subject) %>%
  summarise_all(sum) %>%
  dplyr::rename(agg_tot = agg, cilp_tot = cilp, 
                eno_tot = eno, vf_tot = vf, ra_tot = ra,
                flu_tot = flu, none_tot = none)

for_logistic_models = tmr_distrib_for_export %>% 
  mutate(none = total_events - (agg+cilp+eno+vf+flu)) %>%
  dplyr::rename(Aggrecan_in_MC = agg, Cilp_in_MC = cilp, Enolase_in_MC = eno, 
                Vimentin_Fibrinogen_in_MC = vf, RA_in_MC = ra, Influenza_in_MC = flu, 
                NonSpec_in_MC = none, Cells_in_MC = total_events) %>%
  dplyr::select(-starts_with("pct")) %>%
  left_join(tmr_by_subj) %>%
  dplyr::rename(Aggrecan_tot = agg_tot, Cilp_tot = cilp_tot, Enolase_tot = eno_tot,
                Vimentin_Fibrinogen_tot = vf_tot, RA_tot = ra_tot, Influenza_tot = flu_tot, 
                NonSpec_tot = none_tot, Cells_tot = total, sample = subject) %>%
  inner_join(group_info) %>%
  arrange(sample, metacluster)
write_csv(
  for_logistic_models,
  file = 
    file.path(
      dir_heatmaps,
      "metacluster_counts_for_modeling.csv"))
```

##============================================
## Plot cell distribution across metaclusters
##============================================


```{r mosaic_plots}
# Organize data
mosaic_data =
  events_w_metaclust %>%
  dplyr::select(sample, tmr_pos, metacluster) %>%
  inner_join(group_info %>% 
              dplyr::select(sample, group)) %>%
  dplyr::filter(!(group %in% c("RA-Conv", "2ndYrRAConv"))) %>%
  droplevels()
  
total_cd4_mosaic = mosaic_data %>%
  dplyr::filter(tmr_pos == "none")

# Plot total cd4+ data
ggplot(data = total_cd4_mosaic) +
    geom_mosaic(aes(x = product(metacluster, tmr_pos), fill=metacluster), na.rm=TRUE) + 
    labs(y = "", x = " ", title='CD4+ phenotypes\nfrom all subjects') +
    scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
ggsave(filename = file.path(dir_mosaic_plots, "summary_of_all_CD4s_all_subj.pdf"),
       width = 4, height = 6)

ggplot(data = total_cd4_mosaic) +
    geom_mosaic(aes(x = product(metacluster, sample), fill=metacluster), na.rm=TRUE) + 
    labs(y = "", x = " ", title='CD4+ phenotypes from each subject') +
    scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank())
ggsave(filename = file.path(dir_mosaic_plots, "summary_of_all_CD4s_by_subj.pdf"),
       width = 9, height = 6)

ggplot(data = total_cd4_mosaic, aes(x = factor(group), fill = factor(metacluster))) +
  geom_bar(position = "fill") +
  labs(y = "", x = "", title='CD4+ phenotypes') +
  scale_fill_manual("Aligned Cluster", values = all_tmr_zscore_anno_colors$group) +
  theme(plot.title = element_text(hjust = 0.5),
  axis.text.y = element_blank(),
  axis.ticks.y = element_blank())

ggplot(data = total_cd4_mosaic) +
    geom_mosaic(aes(x = product(metacluster, group), fill=metacluster), na.rm=TRUE) + 
    labs(y = "", x = " ", title='CD4+ phenotypes\nfrom all subjects') +
    scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank())
ggsave(filename = file.path(dir_mosaic_plots, "summary_of_all_CD4s_by_group.pdf"),
       width = 4, height = 6)

# Plot total Tmr+ distribution (by antigen; by group)
total_ra_tmr_mosaic = mosaic_data %>%
  dplyr::filter(tmr_pos != "none",
                tmr_pos != "flu")

ggplot(data = total_ra_tmr_mosaic) +
    geom_mosaic(aes(x = product(metacluster, tmr_pos), fill=metacluster), na.rm=TRUE) + 
    labs(y = "", x = " ", title='RA Tmr+ phenotypes\nfrom all subjects') +
    scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank())
ggsave(filename = file.path(dir_mosaic_plots, "summary_of_all_Tmrs_all_subj.pdf"),
       width = 6, height = 4)

ggplot(data = total_ra_tmr_mosaic) +
    geom_mosaic(aes(x = product(metacluster, group), fill=metacluster), na.rm=TRUE) + 
    labs(y = "", x = " ", title='Pooled RA Tmr+ phenotypes\nfrom all subjects') +
    scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank())
ggsave(filename = file.path(dir_mosaic_plots, "summary_of_all_Tmrs_by_group.pdf"),
       width = 6, height = 4)

# Plot cell distribution summaries by specificity across all subjects & by each subject  
plot_tmr_summary = function(tmr_spec, mosaic_df, size_filter = F){
  if(size_filter == T){
    filtered_data = mosaic_df %>%
      if(tmr_spec == "ra"){
        dplyr::filter(tmr_pos %in% c("agg", "cilp", "eno", "vf")) 
      } else {
        dplyr::filter(tmr_pos == tmr_spec) 
        } %>%
    if(tmr_spec == "agg") {
        dplyr::filter(sample %in% tmr_by_subj$subject[tmr_by_subj$agg_tot >= n_metaclusters])
      } else if(tmr_spec == "cilp") {
        dplyr::filter(sample %in% tmr_by_subj$subject[tmr_by_subj$cilp_tot >= n_metaclusters])
      } else if(tmr_spec == "eno") {
        dplyr::filter(sample %in% tmr_by_subj$subject[tmr_by_subj$eno_tot >= n_metaclusters])
      } else if(tmr_spec == "vf") {
        dplyr::filter(sample %in% tmr_by_subj$subject[tmr_by_subj$vf_tot >= n_metaclusters])
      } else if(tmr_spec == "ra") {
        dplyr::filter(sample %in% tmr_by_subj$subject[tmr_by_subj$ra_tot >= n_metaclusters])
      } else if(tmr_spec == "flu") {
        dplyr::filter(sample %in% tmr_by_subj$subject[tmr_by_subj$flu_tot >= n_metaclusters])
      } %>%
      droplevels()
  } else {
    if(tmr_spec == "ra") {
      filtered_data = filtered_data = mosaic_df %>%
        dplyr::filter(tmr_pos %in% c("agg", "cilp", "eno", "vf"))
    } else {
      filtered_data = filtered_data = mosaic_df %>%
        dplyr::filter(tmr_pos == tmr_spec)
    }
  }
  
  ggplot(data = filtered_data) +
      geom_mosaic(aes(x = product(metacluster, tmr_pos), fill=metacluster), na.rm=TRUE) + 
      labs(y = "", x = " ", title=paste(tmr_spec, 'Tmr+ phenotypes\nfrom all subjects')) +
      scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
      theme(plot.title = element_text(hjust = 0.5),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank())
  ggsave(filename = file.path(dir_mosaic_plots, paste0("summary_of_", tmr_spec, "_all_subj.pdf")), 
         width = 4, height = 6)
  
  ggplot(data = filtered_data) +
      geom_mosaic(aes(x = product(metacluster, group), fill=metacluster), na.rm=TRUE) + 
      labs(y = "", x = " ", title=paste(tmr_spec, 'Tmr+ phenotypes\nfrom all subjects')) +
      scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
      theme(plot.title = element_text(hjust = 0.5),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank())
  ggsave(filename = file.path(dir_mosaic_plots, paste0("summary_of_", tmr_spec, "_by_group.pdf")), 
         width = 4, height = 6)
  
  ggplot(data = filtered_data) +
    geom_mosaic(aes(x = product(metacluster, sample), fill=metacluster), na.rm=TRUE) + 
    labs(y = "", x = " ", title=paste(tmr_spec, 'Tmr+ phenotypes\nfrom each subject')) +
    scale_fill_manual("Metacluster", values = all_tmr_zscore_anno_colors$group) + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank())
  ggsave(filename = file.path(dir_mosaic_plots, paste0("summary_of_", tmr_spec, "_by_subj.pdf")),
         width = 9, height = 6)
}

## Ideally, you should set size_filter = T here.  My sample data didn't have a sufficient number of Tmr+ cells
lapply(c("agg", "cilp", "eno", "vf", "ra", "flu"), plot_tmr_summary, mosaic_data, size_filter = F)
```

```{r write_out_data_for_mosaic_plots}
# want to export total events in each category as well
mosaic_data %>%
  group_by(sample, group, tmr_pos, metacluster) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  tidyr::complete(
    nesting(sample, group), tmr_pos, metacluster,
    fill = list(count = 0)) %>%
  group_by(sample, group, tmr_pos) %>%
  mutate(total_by_sample_tmr_pos = sum(count),
         percent_in_sample_tmr_pos = count / total_by_sample_tmr_pos * 100) %>%
  ungroup() %>%
  dplyr::arrange(group, sample, tmr_pos, metacluster) %>%
  writexl::write_xlsx(
    path = 
      file.path(
        dir_data_output,
        "metacluster_percentages_by_sample_long.xlsx"),
    format_headers = FALSE)
```


```{r specific_cd4_dotplots}
ggplot(data = tmr_counting_tot_sub %>% 
         dplyr::filter(!is.na(group), metacluster %in%  c(6,8)), 
       aes(x = factor(metacluster), y = pct_cd4*100, fill = group)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(aes(shape = group),
               position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.75), 
               size = 2, alpha = 0.5, shape = 1) +
    labs(x = "Metacluster", y = "% Total CD4+") +
    scale_fill_manual("Group", values = c("white", "grey88", "grey77", "grey66")) 

ggplot(data = tmr_counting_tot_sub %>% 
         dplyr::filter(!is.na(group), metacluster %in%  c(4,5)), 
       aes(x = factor(metacluster), y = pct_cd4*100, fill = group)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(aes(shape = group),
               position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.75), 
               size = 2, alpha = 0.5, shape = 1) +
    labs(x = "Metacluster", y = "% Total CD4+") +
    scale_fill_manual("Group", values = c("white", "grey88", "grey77", "grey66")) 

ggplot(data = tmr_counting_tot_sub %>% 
         dplyr::filter(!is.na(group), metacluster %in%  c(1,2)), 
       aes(x = factor(metacluster), y = pct_cd4*100, fill = group)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(aes(shape = group),
               position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.75), 
               size = 2, alpha = 0.5, shape = 1) +
    labs(x = "Metacluster", y = "% Total CD4+") +
    scale_fill_manual("Group", values = c("white", "grey88", "grey77", "grey66")) 

ggplot(data = tmr_counting_cilp_sub %>% 
         dplyr::filter(!is.na(group), metacluster %in%  c(4, 6)), 
       aes(x = factor(metacluster), y = pct_cilp*100, fill = group)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(aes(shape = group),
               position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.75), 
               size = 2, alpha = 0.5, shape = 1) +
    labs(x = "Metacluster", y = "% Cilp-specific CD4+") +
    scale_fill_manual("Group", values = c("white", "grey88", "grey77", "grey66")) 
```

